# Generated by Django 4.2.6 on 2025-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0003_alter_failures_correctiveactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='analysis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='failures',
            name='rootCauseCategory',
            field=models.CharField(choices=[('Material', 'Material'), ('Workmanship', 'Workmanship'), ('NDF', 'NDF'), ('Operador', 'Operador')], default='NDF', max_length=20, verbose_name='Categoría de causa raíz'),
        ),
    ]
