from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('forms_db', '0005_consolidated_migration'),  # Usa el número real
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
                ('uut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut')),
            ],
        ),
    ]# Generated by Django 4.2.6 on 2025-07-04 10:11
