# Generated by Django 4.2.6 on 2025-08-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0004_employes_qa_alter_failures_analysis_and_more'),
        ('forms_db', '0006_create_testhistory'),
    ]

    operations = [
    ]
