# Generated by Django 4.2.6 on 2025-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0007_merge_20250821_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
