# Generated by Django 4.2.6 on 2025-09-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0006_alter_station_stationproject'),
        ('forms_db', '0008_alter_testhistory_id'),
    ]

    operations = [
    ]
