# Generated by Django 5.2.6 on 2025-11-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0009_merge_20250925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booms',
            name='project',
            field=models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY'), ('ROWM', 'ROWM')], max_length=20),
        ),
    ]
