# Generated by Django 4.2.2 on 2025-05-08 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booms',
            fields=[
                ('pn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=125)),
                ('commodity', models.CharField(max_length=50)),
                ('product', models.CharField(choices=[('Senna', 'Senna'), ('Pathfinder', 'Pathfinder'), ('Sojouner', 'Sojouner'), ('Hook', 'Hook'), ('Outlander', 'Outlander'), ('Minerrall Well', 'Minerrall Well'), ('MMCs', 'MCCs'), ('Fornax SAM', 'Fornax SAM'), ('Fornax DIB', 'Fornax DIB'), ('Fornax CIT', 'Fornax CIT'), ('Indus DIB', 'Indus DIB'), ('Indus BOP', 'Indus BOP'), ('Indus SAM', 'Indus SAM'), ('Indus CIT', 'Indus CIT'), ('PMDU', 'PMDU'), ('Switch', 'Switch'), ('Kura', 'Kura'), ('Sled', 'Sled'), ('Rack', 'Rack')], max_length=30)),
                ('ubiLogic', models.CharField(max_length=15)),
                ('project', models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('employeeNumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employeeName', models.CharField(max_length=100)),
                ('pmd', models.BooleanField(default=False)),
                ('dell', models.BooleanField(default=False)),
                ('switch', models.BooleanField(default=False)),
                ('sony', models.BooleanField(default=False)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('privileges', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('pn_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='Failures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateTimeField(auto_now=True)),
                ('analysis', models.CharField(max_length=100)),
                ('rootCause', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('defectSymptom', models.CharField(max_length=100)),
                ('shiftFailure', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=13)),
                ('correctiveActions', models.CharField(choices=[('Resettled subassy and slaves parts', 'Resettled subassy and slaves parts'), ('Retest in another tester', 'Retest in another tester'), ('Retest no touch', 'Retest no touch'), ('Change component', 'Change component'), ('Clean component', 'Clean component'), ('reset equipment and retest', 'reset equipment and retest')], max_length=100)),
                ('imgEvindence', models.ImageField(blank=True, null=True, upload_to='evidences/')),
                ('log', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('comments', models.TextField()),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('id_er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.errormessages')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationProject', models.CharField(choices=[('DELL', 'DELL'), ('PMDU', 'PMDU'), ('1G-SW', '1G-SW'), ('SONY', 'SONY')], max_length=50)),
                ('stationName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('pn_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('employee_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
                ('uut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('serial', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nicho', models.CharField(choices=[('AB19_P01', 'AB19_P01'), ('AB19_P02', 'AB19_P02'), ('AB19_P03', 'AB19_P03'), ('AB19_P04', 'AB19_P04'), ('AB19_P06', 'AB19_P06'), ('AB19_P08', 'AB19_P08'), ('AB19_P09', 'AB19_P09'), ('AB19_P10', 'AB19_P10'), ('AB19_P11', 'AB19_P11'), ('AB19_P12', 'AB19_P12'), ('AB20_P01', 'AB20_P01'), ('AB20_P02', 'AB20_P02'), ('AB20_P03', 'AB20_P03'), ('AB20_P04', 'AB20_P04'), ('AB20_P06', 'AB20_P06'), ('AB20_P08', 'AB20_P08'), ('AB20_P09', 'AB20_P09'), ('AB20_P10', 'AB20_P10'), ('AB20_P11', 'AB20_P11'), ('AB20_P12', 'AB20_P12')], max_length=10)),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('cims', models.ImageField(null=True, upload_to='media/')),
                ('crabber', models.ImageField(null=True, upload_to='media/')),
                ('employee_e', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRejected', models.DateTimeField(auto_now=True)),
                ('snDamaged', models.CharField(max_length=50)),
                ('snNew', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=15)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.failures')),
                ('pn_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.booms')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceType', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective')], max_length=100)),
                ('dateStart', models.DateTimeField(auto_now_add=True)),
                ('dateFinish', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('failureM', models.CharField(default='N/A', max_length=100)),
                ('causeCategoryS', models.CharField(default='N/A', max_length=100)),
                ('employee_e', models.ForeignKey(blank=True, default='ex', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes')),
                ('id_sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.sparepart')),
                ('station_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.station')),
            ],
        ),
        migrations.AddField(
            model_name='failures',
            name='id_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.station'),
        ),
        migrations.AddField(
            model_name='failures',
            name='sn_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_db.uut'),
        ),
        migrations.AddField(
            model_name='booms',
            name='employee_e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_db.employes'),
        ),
    ]
