# Generated by Django 4.2.2 on 2025-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failures',
            name='rootCauseCategory',
            field=models.CharField(choices=[('Material', 'Material'), ('Workmachine', 'Workmachine'), ('NDF', 'NDF'), ('Operador', 'Operador')], default='NDF', max_length=20, verbose_name='Categoría de causa raíz'),
        ),
        migrations.AlterField(
            model_name='errormessages',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='failures',
            name='correctiveActions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
