# Generated by Django 4.2.2 on 2025-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0002_failures_rootcausecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failures',
            name='correctiveActions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='failures',
            name='rootCause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
