# Generated by Django 4.2.6 on 2025-07-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_db', '0004_alter_failures_analysis_and_more'),
    ]

    operations = [
    ]
